package models

type Computer struct {
	UID                             string         `json:"uid"`
	Description                     string         `json:"description"`
	WatchmanID                      string         `json:"watchman_id"`
	ClientID                        string         `json:"client_id"`
	AgentVersion                    string         `json:"agent_version"`
	BuildNumber                     string         `json:"build_number"`
	LastReport                      int            `json:"last_report"`
	CreatedAt                       int            `json:"created_at"`
	Group                           string         `json:"group"`
	ComputerName                    string         `json:"computer_name"`
	CustomName                      string         `json:"custom_name"`
	ComputerURL                     string         `json:"computer_url"`
	ContactEmail                    string         `json:"contact_email"`
	ReferenceEmail                  string         `json:"reference_email"`
	ReferenceEmailComputer          string         `json:"reference_email_computer"`
	ReferenceEmailGroup             string         `json:"reference_email_group"`
	LastUser                        string         `json:"last_user"`
	SerialNumber                    string         `json:"serial_number"`
	OsVersion                       string         `json:"os_version"`
	OsVersionNumber                 string         `json:"os_version_number"`
	OsVersionNumberMax              string         `json:"os_version_number_max"`
	ModelIdentifier                 string         `json:"model_identifier"`
	AppleProductDescription         string         `json:"apple_product_description"`
	ProductDescription              string         `json:"product_description"`
	EstimatedManufactureDate        any            `json:"estimated_manufacture_date"`
	RAMInstalled                    string         `json:"ram_installed"`
	RAMInstalledInBytes             string         `json:"ram_installed_in_bytes"`
	RAMSpeed                        string         `json:"ram_speed"`
	RAMUpgradeable                  bool           `json:"ram_upgradeable"`
	RAMMaxApple                     string         `json:"ram_max_apple"`
	RAMMaxActual                    string         `json:"ram_max_actual"`
	BootVolumeCapacity              string         `json:"boot_volume_capacity"`
	BootVolumeUsage                 string         `json:"boot_volume_usage"`
	BootVolumeUsagePercent          string         `json:"boot_volume_usage_percent"`
	Processor                       string         `json:"processor"`
	CurrentUptime                   string         `json:"current_uptime"`
	RawUptime                       int            `json:"raw_uptime"`
	SmcVersion                      string         `json:"smc_version"`
	PrimaryIP                       string         `json:"primary_ip"`
	ActiveMacAddress                string         `json:"active_mac_address"`
	SystemMacAddress                string         `json:"system_mac_address"`
	AssetID                         string         `json:"asset_id"`
	ArdField1                       string         `json:"ard_field1"`
	ArdField2                       string         `json:"ard_field2"`
	ArdField3                       string         `json:"ard_field3"`
	ArdField4                       string         `json:"ard_field4"`
	TeamviewerID                    string         `json:"teamviewer_id"`
	TeamviewerRelease               string         `json:"teamviewer_release"`
	TeamviewerUnattended            bool           `json:"teamviewer_unattended"`
	BomgarURL                       string         `json:"bomgar_url"`
	LogmeinURL                      string         `json:"logmein_url"`
	SimplehelpURL                   string         `json:"simplehelp_url"`
	JssComputerID                   string         `json:"jss_computer_id"`
	JssURL                          string         `json:"jss_url"`
	MunkiIdentifier                 string         `json:"munki_identifier"`
	InternalNotes                   string         `json:"internal_notes"`
	PublicNotes                     string         `json:"public_notes"`
	UpdatesEnabled                  bool           `json:"updates_enabled"`
	SettingsEnabled                 bool           `json:"settings_enabled"`
	ReportIfMissing                 bool           `json:"report_if_missing"`
	ReportMissingAfter              int            `json:"report_missing_after"`
	IgnoreMissingUntil              string         `json:"ignore_missing_until"`
	RekeyRequested                  bool           `json:"rekey_requested"`
	PendingRemoval                  bool           `json:"pending_removal"`
	AgentRemoved                    bool           `json:"agent_removed"`
	HasIssue                        bool           `json:"has_issue"`
	Missing                         bool           `json:"missing"`
	Hidden                          bool           `json:"hidden"`
	Platform                        string         `json:"platform"`
	BeaconReporting                 bool           `json:"beacon_reporting"`
	BeaconMissingThresholdInMinutes int            `json:"beacon_missing_threshold_in_minutes"`
	CreateTicketOnBeaconFound       bool           `json:"create_ticket_on_beacon_found"`
	PluginResults                   []PluginResult `json:"plugin_results"`
}
